config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index' # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 5 }
  validates :author, presence: true, length: { maximum: 55, minimum: 5 }
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
   @quote = Quote.order("RANDOM()").first
  end


  def create
    @quote = Quote.create(quote_params)
      if @quote.invalid?
          flash[:error] = '<strong> How dare you!</strong> You have not entered a valid thing'
        end
    redirect_to root_path
  end 

  def about

  end

  private 

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style> 
      @import url('https://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900|Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&display=swap');
    </style>

  </head>

  <body>
    <header class="row">
      <div class="col-2">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />WE
            <br />MAKE
            <br />THINGS
          </div>
        <% end %>
      </div>

      <div class= "col-4 hidden-xs-down slogan" >
        Splurting out unsolicited advice about entrepreneurship since 2016
      </div>

      <div class= "col-10 offset-1 offset-sm-0 col-sm-5 links">

        <%= link_to 'Contribute', new_quote_path, data: {toggle: 'modal', target: '#myModal'} %><!-- Button trigger modal -->
        <%= link_to  'About', about_path %>
      </div>

    </header>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModal">Contribute Your Quote</h4>
          </div>
          <div class="modal-body">
            <h1> Enter Your Quote Details </h1>
              <%= simple_form_for Quote.new do |f| %>
                <%= f.input :saying, label: "What is the quote you are adding?", placeholder: "This is where you write it"%>
                <br />
                <%= f.input :author, label: "Who wrote it?", placeholder: "This is who wrote it" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit 'Create', class: 'btn btn-primary ' %>
           </div>
           <% end %>   
        </div>
      </div>
    </div>

     <br class="clear" />

    <div class="container">
      <% if flash[:error].present? %>
        <div class="col-10 offset-1 alert alert-danger">
            <%= flash[:error].html_safe %>
        </div>
      <% end %> 
       <%= yield %>
     </div>

     <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
           <%= link_to 'We break things...', root_path, class: 'next_quote' %>
          </div>
          <div class="col-12 col-sm-6 footer_blurb">
            I broke this : <a href="tomwsanders.com">Batman</a><br />
            You can to! <a href="apple.com">Hello</a>
          </div>
        </div>
      </div>
     </div>
  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-12 about">
    <h1>About Splurty</h1>
   <p>
    Splurty was built by <a target="_blank" href="https://twitter.com/benaffleck">Ben</a> & <a target="_blank" href="https://twitter.com/robpattinsonww?lang=en&lang=en">Robert</a>. Two web developers who are on a mission to give people the technical skills needed to launch their own MVPs and turn ideas into reality. </p>
  <p>
    In the name of his murdered parents, Bruce Wayne wages eternal war on the criminals of Gotham City. He is vengeance. He is the night. He is Batman.
  </p>
  <p>
    If you want to learn how - start <a target="_blank" href="https://www.dccomics.com/characters/batman"> here</a>.
  </p>

  <br class="clear" />

  <div class="row">
      <div class="col-12 col-sm-3 center">
        <%= image_tag 'ben.jpg', class: 'img-fluid bio_pic' %>
      </div>

      <div class="col-12 col-sm-8 offset-sm-1">
        <h2 class="text-left bio_padding"> Ben Affleck </h2>
        <p> Ben Affleck just started playing Batman two years ago, but it seems he’s just about ready to retire as the character. Over the past few months, the evidence that Affleck won’t be Batman for much longer has piled up. Now, it’s been all but confirmed that Justice League will have been his final time depicting the Caped Crusader. </p>
        <p> So what has been the evidence that Affleck is ready to stop playing Batman? </p>
      </div>
  </div>

  <br class="clear" />

  <div class="row">
    <div class="col-12 col-sm-3 center">
      <%= image_tag 'pat.jpg', class: 'img-fluid bio_pic' %>
    </div>

    <div class="col-12 col-sm-8 offset-sm-1">
      <h2 class="text-left bio_padding"> Robert Pattinson </h2>
      <p> Robert Pattinson is the new Batman, and fans have mixed feelings about the young star wearing the cape. </p>
      <p> Rumors had been flying faster than a Batarang about who’s going to play the next Batman since Ben Affleck isn’t returning. It came down to a seeming close call between Robert Pattinson and Nicholas Hoult. Of course, with both being British, it created social media debates about whether a Brit should play Batman. </p>
    </div>
  </div>
</div>

app/views/quotes/index.html.erb
<h2>
  <span>SPLURTY / No. <%= @quote.id %></span>
  Here's the <u>best unsolicited startup advice</u> you can get!
</h2>
<br />
<br />
<h1><%= @quote.saying %></h1>
<h2 class="float-right"> <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/new.html.erb
<h1> Enter Your Quote Details </h1>
  <%= simple_form_for @quote do |f| %>
    <%= f.input :saying %>
    <%= f.input :author %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary ' %>
  <% end %> 